name: test

on:
  push:
    branches: [ main, vault_connexion ]

permissions:
  id-token: write

jobs:
  test-vault:
    runs-on: ubuntu-latest

    steps:
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_URL }}
          method: jwt
          role: ${{ secrets.ROLE }}
          jwtGithubAudience: ${{ secrets.JWT_GIT_AUDIENCE }}
          secrets: |
            ${{ secrets.VAULT_VPS_SSH_SERVER_IP }} | VPS_SERVER_IP
            ${{ secrets.VAULT_VPS_SSH_SERVER_PASS }} | VPS_SSH_SERVER_PASS
            ${{ secrets.VAULT_SSH_PRIVATE_KEY }} | SSH_PRIVATE_KEY